on:
    push:
        branches:
            - '**'
        tags:
            - 'NEVER'
    pull_request:
        types: [opened, reopened]

env:
    APT: sudo apt install -y --no-install-recommends
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
    CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options

jobs:
    gh_pages:
        runs-on: ubuntu-22.04

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
                fetch-depth: 0
            - run: $APT doxygen
            - run: make dox
            - run: |
                cd doc/dox
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add *
                git commit -a -m "Automated update"
                git push
